In [2]:
import re
import pandas as pd
import dotenv
import os
from neo4j import GraphDatabase

In [3]:
triplets_df_path = "../data/gfmag_sustainable_triplets.csv"
NEO4J_ENV = "../Neo4j-6b4d3211-Created-2026-01-22.txt"

In [4]:
triplets_df = pd.read_csv(triplets_df_path)
triplets_df.rename(columns={"industry":"sector"}, inplace=True)
triplets_df["sector"] = triplets_df["sector"].str.lower()

In [5]:
triplets_df[triplets_df["entity1"]=="China"]

,entity1,entity1_type,rel_type,entity2,entity2_type,sector,url,date
0,China,country,is_member_of,Renewable energy,economic_indicator,energy,https://gfmag.com/sustainable-finance/coal-tak...,2025-11-09T09:30:00+00:00
412,China,country,controls,coal power plants,product,energy,https://gfmag.com/sustainable-finance/new-grow...,2023-02-05T00:00:00+00:00
450,China,country,is_member_of,COP27,event,climate,https://gfmag.com/features/cop27-tangible-prog...,2022-11-09T00:00:00+00:00
504,China,country,has_negative_impact,US,country,other,https://gfmag.com/sustainable-finance/commodit...,2022-09-01T00:00:00+00:00
1058,China,country,relates_to,carbon emissions,economic_indicator,climate,https://gfmag.com/economics-policy-regulation/...,2014-12-17T00:00:00+00:00
1060,China,country,relates_to,US,country,economy,https://gfmag.com/economics-policy-regulation/...,2014-12-17T00:00:00+00:00
1062,China,country,relates_to,greenhouse gas emissions,economic_indicator,climate,https://gfmag.com/economics-policy-regulation/...,2014-12-17T00:00:00+00:00
1116,China,country,has_negative_impact,Emerging markets,economic_indicator,economy,https://gfmag.com/economics-policy-regulation/...,2013-12-02T00:00:00+00:00

In [8]:
load_to_neo4j(df=triplets_df, env_file=NEO4J_ENV)

Graph data loaded to Neo4j successfully.

# clear neo4j

In [ ]:
from neo4j import GraphDatabase
import os
import dotenv
# removing all

# Load your Aura credentials
dotenv.load_dotenv(".env")
URI = os.getenv("NEO4J_URI")
USER = os.getenv("NEO4J_USERNAME")
PWD = os.getenv("NEO4J_PASSWORD")

driver = GraphDatabase.driver(URI, auth=(USER, PWD))

with driver.session() as session:
    session.run("MATCH (n) DETACH DELETE n")

driver.close()
print("Database cleared successfully.")

# data inspect

In [6]:
sectors = pd.read_csv("neo4j_query_table_data_2026-2-5.csv")

In [12]:
sectors["r.sector"] = sectors["r.sector"].str.lower()

In [20]:
sectors.drop_duplicates(inplace=True)

In [24]:
ALLOWED_SECTORS = {
    "financials",
    "technology",
    "healthcare",
    "real estate",
    "industrials",
    "transportation",
    "energy",
    "consumer goods and services",
    "natural resources",
    "public sector",
    "other"
}

In [25]:
sectors[~sectors["r.sector"].isin(ALLOWED_SECTORS)]

                r.sector
4               politics
6                climate
13         trade surplus
15             education
18           environment
..                   ...
256    wealth management
257     zimbabwe:country
259     financial sector
261      loan portfolios
262  rising credit costs

[192 rows x 1 columns]